# Generated by Django 5.2.5 on 2025-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Non Aktif')], default='active', max_length=10)),
                ('delivery_status', models.CharField(choices=[('delivery', 'Delivery'), ('non_delivery', 'Non Delivery')], default='delivery', max_length=15)),
                ('qty_total', models.IntegerField(default=0)),
            ],
        ),
    ]
