# Generated by Django 5.2.5 on 2025-08-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=20, unique=True)),
                ('nama_barang', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_barang/')),
                ('status_barang', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Non Aktif')], default='aktif', max_length=10)),
                ('status_pengiriman', models.CharField(choices=[('delivery', 'Delivery'), ('non_delivery', 'Non Delivery')], default='delivery', max_length=15)),
                ('qty_total', models.IntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
