# Generated by Django 5.2.5 on 2025-08-15 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_barang_delete_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('IN', 'Barang Masuk'), ('OUT', 'Barang Keluar')], max_length=3)),
                ('qty', models.PositiveIntegerField()),
                ('status_barang', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Non Aktif')], default='aktif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='warehouse.barang')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
