# Generated by Django 5.2.5 on 2025-08-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_barang_id_transaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=200)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
